homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 100
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret http_base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

automation: !include includes/automations.yaml
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml
script: !include includes/scripts.yaml
zone: !include includes/zones.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://hassio.local:3218/
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html
    
ios:

device_tracker:
  - platform: owntracks

switch:
  - platform: tplink
    host: 192.168.0.37
    name: "Electric Blanket"
    
apple_tv:
  - host: 192.168.0.24
    login_id: !secret apple_tv_login
    start_off: true
  - host: 192.168.0.32
    login_id: !secret apple_tv_login
    start_off: true

hue:
  bridges:
    - host: 192.168.0.29
      filename: phue.conf
      allow_hue_groups: false
    - host: 192.168.0.12
      filename: phue2.conf
      allow_hue_groups: false
      
mqtt:
  embedded:
