- alias: "Turn on evening tv scene when apple tv is playing"
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: media_player.toms_apple_tv_room
    to: 'playing'
    from: 'paused'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.evening_tv

- alias: "When ATV is playing then paused turn off evening scene"
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: media_player.toms_apple_tv_room
    to: 'paused'
    from: 'playing'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.evening_tv_paused
